### PR TITLE
Fix for deserializing local refs within item schemas

### PR DESCRIPTION
**Pull request by kevin-secrist**
Hi there,

After the most recent update, I've been running into issues deserializing schemas of a certain shape. It looks like it's likely related to https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/78, but I haven't been able to figure out exactly what the fix is yet.

I've added a failing unit test showing the error that I'm experiencing. Any advice would be appreciated, thanks!

### CODE REVIEW

**Comment by kevin-secrist** [comment]
It took me a little bit to figure out how to debug the unit test so I could see what was happening. Disabling Resharper seemed to do it. I don't know why but Resharper really doesn't agree with the unit tests. After doing so I was able to debug and inspect what was happening and where the code may need a change.

I've added a check that mirrors the change here https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/0f12bdc3373be58f6f8785b9ea7b41ced1f05f19#diff-7d044639573197defe5cc2d234a2efddR107 and it appears to resolve the issue, however I don't fully understand the purpose of the `ItemsPositionValidation` so there's a good chance what I'm doing is naïve.

**Comment by JamesNK** [comment]
Thanks for the PR!

`ItemsPositionValidation` is a flag that is used to differentiate between validating an array using one schema or having multiple schemas, and the schema chosen is passed on the position.

More info: http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.9

**Comment by kevin-secrist** [comment]
Interesting, I had no idea that was in the spec. Thanks for the clarification. I have a more accurate fix but I'm still working on the test.

**Comment by kevin-secrist** [comment]
How does that look?

**Comment by JamesNK** [comment]
Good, although I made the items position check more explicit https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/000560a1519778e26d986a84036378ec087e430b

Thanks

**Comment by creque** [comment]
Thanks for the turnaround on getting this merged!  What kind of timetable do you think there will be for a release on this?  We're holding on a couple of releases, but if it's going to be awhile, we'll have to roll back to the previous version, which we'd really like to avoid

**Comment by JamesNK** [comment]
New version for you - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.10

**Pull request merged**
